[project]
name = "advent2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "wasmtime>=39.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.7",
]
